FROM ubuntu:22.04

# 1. 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip \
        python3.10-dev \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

# 2. workdir 설정
WORKDIR /vllm

# 3. pip 업그레이드 및 필요한 패키지 설치
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# 4. 애플리케이션 소스 복사
COPY . .

# 5. 포트 노출
EXPOSE 8000

# 6. entrypoint.sh 실행 
ENTRYPOINT ["./entrypoint.sh"]
CMD []